= Assets
:nofooter:

[plantuml, target=vector, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono ExtraBold

class User {
  .. Member functions ..
  + constructor
  + destructor
  + operator=
  .. Capacity ..
  + size
  + max_size
  + resize
  + capacity
  + empty
  + reserve
  + shrink_to_fit
  .. Element access ..
  + operator[]
  + at
  + front
  + back
  + data
  .. Modifiers ..
  + assign
  + push_back
  + pop_back
  + insert
  + erase
  + swap
  + clear
  + emplace
  + emplace_back
  .. Allocator ..
  + get_allocator
  __ private data __
  T *list;
  unsigned int _maxSize
  unsigned int _size
}

@enduml
....

[gnuplot, target=gnuplot, format=svg, width=100%]
....
# set terminal pngcairo  transparent enhanced font "arial,10" fontscale 1.0 size 600, 400
# set output 'simple.5.png'
set key fixed left top vertical Right noreverse enhanced autotitle box lt black linewidth 1.000 dashtype solid
set samples 400, 400
set title "Size of the vector"
set title  font ",20" textcolor lt -1 norotate
set xrange [ * : *  ] noreverse writeback
set x2range [ * : *  ] noreverse writeback
set yrange [ * : *  ] noreverse writeback
set y2range [ * : *  ] noreverse writeback
set zrange [ * : *  ] noreverse writeback
set cbrange [ * : *  ] noreverse writeback
set rrange [ * : *  ] noreverse writeback
NO_ANIMATION = 1
plot [0:10]  2**x
....
