= Assets
:nofooter:

== Map

[plantuml, target=map_usecase, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

actor user

package map {
	usecase "insert"
	usecase "erase"
}

package "red black tree" as rbt {
	usecase "rotate"
}

user --> insert
user --> erase
map  --> rbt

@enduml
....


== Red black

=== deletion

[plantuml, target=rbt_delete, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

start
if (node is alone and is the root) then (yes)
  :_root = 0;
  stop
else (no)
endif

if (node is leaf) then (yes)

  if (node is red) then (yes)
    :delete the node;
    stop
  else (no)
  endif
  if (node is black) then (yes)
    :color node double-black;
    :resolve_double_black(node);
    stop
  else (no)
  endif

else (no)
endif

if (node has a red child) then (yes)
  :delete node;
  :promote the child;
  :color child black;
  stop
else (no)
endif

if (node has two children) then (yes)
  :find the predecessor;
  note left
  the predecessor is located
  at rightmost position
  of p's left subtree
  end note
  :replace the node value with his predecessor;
  :erase(predecessor);
  stop
else (no)
endif

end

@enduml
....

=== Resolve double black

[plantuml, target=resolve_double_black, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

start

if (sibling is black and nephew is red) then (yes)
  :rotate between the parent
  and the sibling;
  :color black the nephew, sibling and the parent;
  stop
else (no)
endif

if (sibling is black and has black children) then (yes)
  :color red sibling;

  if (parent is red) then (yes)
    :color black the parent;
    :color red the sibling;
    stop
  else (no)
    if (parent is the root) then (yes)
      stop
    else (no)
      :color double-black the parent;
      :resolve_double_black(parent);
    endif
  endif
  stop
else (no)
endif

if (sibling is red and has black children) then (yes)
  :rotate sibling and parent;
  :resolve_double_black(node);
  stop
else (no)
endif

end

@enduml
....

=== A simple node

[plantuml, target=node, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

map t_node {
    Key => Value
}

@enduml
....

=== Case 0

[plantuml, target=rbt00, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map root #grey {
    15 => "Paul"
}

@enduml
....

=== Case 1

[plantuml, target=rbt10, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map root #grey {
    15 => "Paul"
}

map left_1 #grey {
    5 => "Jean"
}

root --> left_1 : left

@enduml
....

[plantuml, target=rbt11, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map root #grey {
    15 => "Paul"
}

map left_1 #pink {
    5 => "Jean"
}

root --> left_1 : left

@enduml
....

=== Case 2

[plantuml, target=rbt20, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map root #grey {
    15 => "Paul"
}

map left_1 #pink {
    5 => "Jean"
}

map left_2 #pink {
    1 => "Marc"
}

root --> left_1 : left
left_1 --> left_2 : left

@enduml
....

[plantuml, target=rbt21, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map root #grey {
    15 => "Paul"
}

object uncle #grey {
    "NULL"
}

map left_1 #pink {
    5 => "Jean"
}

map left_2 #pink {
    1 => "Marc"
}

root --> left_1 : left
root --> uncle : right
left_1 --> left_2 : left

@enduml
....

[plantuml, target=rbt22, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map right_1 #grey {
    15 => "Paul"
}

map root #pink {
    5 => "Jean"
}

map left_1 #pink {
    1 => "Marc"
}

root --> left_1 : left
root --> right_1 : right

@enduml
....

[plantuml, target=rbt23, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map right_1 #pink {
    15 => "Paul"
}

map root #grey {
    5 => "Jean"
}

map left_1 #pink {
    1 => "Marc"
}

root --> left_1 : left
root --> right_1 : right

@enduml
....

[plantuml, target=vector, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class User {
  .. Member functions ..
  + constructor
  + destructor
  + operator=
  .. Capacity ..
  + size
  + max_size
  + resize
  + capacity
  + empty
  + reserve
  + shrink_to_fit
  .. Element access ..
  + operator[]
  + at
  + front
  + back
  + data
  .. Modifiers ..
  + assign
  + push_back
  + pop_back
  + insert
  + erase
  + swap
  + clear
  + emplace
  + emplace_back
  .. Allocator ..
  + get_allocator
  __ private data __
  T			*_list;
  unsigned long		_maxSize
  unsigned long		_size
  unsigned long		_allocated
  std::allocator<T>	_allocator;
}

@enduml
....

[gnuplot, target=gnuplot, format=svg, width=100%]
....
set grid nopolar
set grid xtics nomxtics ytics nomytics noztics nomztics nortics nomrtics \
 nox2tics nomx2tics noy2tics nomy2tics nocbtics nomcbtics
set grid layerdefault   lt 0 linecolor 0 linewidth 0.500,  lt 0 linecolor 0 linewidth 0.500
set samples 21, 21
set isosamples 11, 11
set style data lines
set xyplane relative 0
set title "Allocation size according\nto the first assignation(x-axis)\nand number of times of reallocation(y-axis)"
set xlabel "Number of elements for\nthe first assignation"
set xlabel  offset character -3, -2, 0 font "" textcolor lt -1 norotate
set xrange [ 0.0000 : 8.0000  ] noreverse nowriteback
set x2range [ * : *  ] noreverse writeback
set ylabel "Number of times\nof reallocation"
set ylabel  offset character 3, -2, 0 font "" textcolor lt -1 rotate
set yrange [ 0.0000 : 5.0000  ] noreverse nowriteback
set y2range [ * : *  ] noreverse writeback
set zlabel ""
set zlabel  offset character -5, 0, 0 font "" textcolor lt -1 norotate
set zrange [ * : *  ] noreverse writeback
set cbrange [ * : *  ] noreverse writeback
set rrange [ * : *  ] noreverse writeback
set colorbox vertical origin screen 0.9, 0.2 size screen 0.05, 0.6 front  noinvert bdefault
NO_ANIMATION = 1
## Last datafile plotted: "$grid"
splot x * 2**y
....
