= Assets
:nofooter:

== Global

=== Class

[plantuml, target=global_class, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class vector

class map

class iteratorMap

class iteratorVector

class stack {
	vector _container
}

struct iterator

iteratorMap <-- iterator
iteratorVector <-- iterator

....


=== Components

[plantuml, target=global_comp, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

package "Standard template library" as stl {
	package "Sequence containers" {
		package "vector" {
			[vector iterator]
		}
	}

	package "Container adaptors" {
		package "stack" {
			[container vector]
		}

	}

	package "Associative containers" {
		package "map" {
			[map iterator]
		}
	}

	package "Iterator traits"

	package "Iterator"

	package "Reverse iterator"

}

@enduml
....

== Map

[plantuml, target=map_usecase, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

actor user

package map {
	usecase "insert"
	usecase "erase"
}

package "red black tree" as rbt {
	usecase "rotate"
}

user --> insert
user --> erase
map  --> rbt

@enduml
....

== Vector

[plantuml, target=vector, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class User {
  .. Member functions ..
  + constructor
  + destructor
  + operator=
  .. Capacity ..
  + size
  + max_size
  + resize
  + capacity
  + empty
  + reserve
  + shrink_to_fit
  .. Element access ..
  + operator[]
  + at
  + front
  + back
  + data
  .. Modifiers ..
  + assign
  + push_back
  + pop_back
  + insert
  + erase
  + swap
  + clear
  + emplace
  + emplace_back
  .. Allocator ..
  + get_allocator
  __ private data __
  T			*_list;
  unsigned long		_maxSize
  unsigned long		_size
  unsigned long		_allocated
  std::allocator<T>	_allocator;
}

@enduml
....
